### ISSUE TITLE
Fail to check device

### ISSUE THREAD

**Issue by BigBenz0** [marian-m12l/studio#40] opened 2020-03-28 16:21 UTC
It seems the last release (0.1.11) fail to check my device.
I am on windows 10 with firefox.

Is it due to an update of Lunii ?

Thanks

**Comment by marian-m12l** [comment] 2020-03-31 20:00
Hi,

Did a quick test after updating the Luniistore, and I'm getting errors when trying to transfer from or to the device, so it looks like the updated libraries are no longer compatible and STUdio will need an update.

**Comment by dasebasto** [comment] 2020-03-31 21:24
> It seems the last release (0.1.11) fail to check my device.
> I am on windows 10 with firefox.
> 
> Is it due to an update of Lunii ?
> 
> Thanks

I have just had the same issue on my second computer.
Problem had nothing to do with STUdio, as the Luniistore itself was not able to recognize the device (unknown error on startup).

I managed to fix this by reinstalling the driver, as instructed here: https://support.lunii.com/hc/fr/articles/360002549678-Comment-r%C3%A9installer-le-pilote-informatique-utilis%C3%A9-par-le-Luniistore-

Now both Luniistore and STUdio detect the device correctly.

**Comment by dasebasto** [comment] 2020-03-31 22:49
After more testing, it appears that the latest Luniistore update:
- breaks the USB driver (which needs reinstalling via `C:\Program Files\Luniistore\app\driver\install-driver.bat`, this fixes STUdio device check error)

- breaks compatibility with STUdio: STUdio shows 0 packs on the device (but no error).
I (recklessly) added a custom pack to the device. It was written as sector 1, even though the device had other packs installed.
Result: device can only play the new pack.
When launched, Luniistore detects a corrupt device and automatically starts to repair it. (still ongoing, I think it is formatting the card and reinstalling the default album).

**Comment by marian-m12l** [comment] 2020-04-01 11:46
Sounds like there is something with the latest libs, I'll need to take more time to understand what's going on.
Also, there seems to be a problem with the reordering feature when transfering a pack from the device, as the app (STUdio) tries to transfer and reorder at the same time...

**Comment by mehdifo** [comment] 2020-04-01 22:35
Hello,
I cannot upload a new created story made with STUdio (0.1.11).
I only have the message "Echec de l'ajout du pack à l'appareil". 
I am on windows 10, the latest version of luniistore (2), and I have uninstall it and reinstall it.

By the way: thank you for this fantastic tool. It is a bit hard to install when you are not a developper, but the idea is great!

**Comment by mehdifo** [comment] 2020-04-02 09:16
If it can help, here is the java messge of the error:

avr. 02, 2020 11:13:34 AM studio.webui.service.StoryTellerService
INFO: Device plugged
avr. 02, 2020 11:13:45 AM studio.webui.service.LibraryService
WARNING: Pack to transfer is in archive format. Converting to binary format and storing in temporary file: C:\Users\Mehdi\AppData\Local\Temp\Les_histoires_de_Papa_1-7bfb15b3-1246-4ad9-82a8-f45cbdf59c37-v1.zip13878310394458210532.pack
avr. 02, 2020 11:13:45 AM studio.webui.service.LibraryService
WARNING: Reading archive format pack
avr. 02, 2020 11:13:45 AM studio.webui.service.LibraryService
WARNING: Uncompressing pack assets
avr. 02, 2020 11:13:45 AM studio.webui.service.LibraryService
SEVERE: Failed to convert archive format pack to binary format
java.io.IOException: Failed to convert image
        at studio.core.v1.utils.ImageConversion.convertImage(ImageConversion.java:37)
        at studio.core.v1.utils.ImageConversion.pngToBitmap(ImageConversion.java:21)
        at studio.core.v1.utils.PackAssetsCompression.withUncompressedAssets(PackAssetsCompression.java:92)
        at studio.webui.service.LibraryService.getBinaryPackFile(LibraryService.java:134)
        at studio.webui.api.DeviceController$1.run(DeviceController.java:66)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
avr. 02, 2020 11:13:45 AM studio.webui.api.DeviceController
SEVERE: Failed to read or convert pack
avr. 02, 2020 11:13:45 AM studio.webui.MainVerticle
SEVERE: Exception thrown
io.vertx.core.impl.NoStackTraceThrowable: Failed to read or convert pack

**Comment by dasebasto** [comment] 2020-04-02 09:26
> If it can help, here is the java messge of the error

This is caused by issue #42 
Quickest workaround is to use JPG or BMP instead of PNG.

**Comment by mehdifo** [comment] 2020-04-02 10:10
> 
> 
> > If it can help, here is the java messge of the error
> 
> This is caused by issue #42
> Quickest workaround is to use JPG or BMP instead of PNG.

Thank you! It worked for me. I have still an issue with the sizes of the pictures, but I will try to figure out a workaround!

**Comment by T1nd4** [comment] 2020-04-02 11:13
> 
> 
> Sounds like there is something with the latest libs, I'll need to take more time to understand what's going on.
> Also, there seems to be a problem with the reordering feature when transfering a pack from the device, as the app (STUdio) tries to transfer and reorder at the same time...

Do you think you will find a solution soon? Is it useful to reinstall the lunistore (with the previous version of course)?

**Comment by marian-m12l** [comment] 2020-04-02 19:55
I took a look yesterday, but I'm not sure what's happening...
After updating to the latest libraries (on windows), it seems to still work at times, and fail sometimes. I noticed that removing other USB devices from the computer (I have a Logitech Unifying receiver that may cause some kind of conflict with libusb4java, the library on which the driver is based) sometimes make it work.

It may help me understand the situation if you could:
* Update to the latest version of the app (compile from `master`)
* Maybe try with / without other USB devices plugged into your computer. STUdio app should be restarted between every try.
* If you get errors, copy the error messages from the logs (in the console) and the HTTP response (in the browser's "network" tab). (I know this is painful, I'm planning to improve the logs and maybe add a mechanism to initiate a github issue directly from an in-browser error)

Also, I fixed the reordering situation (when transferring a pack from the device) which may have caused some errors.

Thanks again for all the feedback!

**Comment by mehdifo** [comment] 2020-04-02 20:00
Just to let you know: it works fine for me!
If you are interested, I can share my stories!
Best regards

**Comment by marian-m12l** [comment] 2020-04-02 20:12
> Just to let you know: it works fine for me!
> If you are interested, I can share my stories!
> Best regards

Thanks!
It's still strange that several people seem to have issues at the same time. And I never had any problem of usb devices conflict previously.
Thanks for offering, but the issue is not related to the story packs. Failure to "check device" (which is the step where we fetch information such as the device serial number and used/free space) implies this is a driver problem.

**Comment by marian-m12l** [comment] 2020-04-04 22:12
I'm closing this issue as I can no longer reproduce it. Feel free to open a new issue if this happens again.

**Closed by marian-m12l** 2020-04-04 22:12 UTC
Labels: bug
