### ISSUE TITLE
STUdio ne se lance plus

### ISSUE THREAD

**Issue by MAcdugels** [marian-m12l/studio#393] opened 2023-09-14 15:13 UTC
Depuis ce matin, impossible de lancer STUdio sur Windows, cmd.exe se lance et plante.
Je suis une méga quiche, je ne connais rien à rien, vous savez m'aider à travers les logs ?
(j'ai passé des plombes à créer une bibliothèque que j'aimerais bien ne pas perdre...)
Merci !

**Logs**
2023-09-14 17:05:50,937 [ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 858 column 174891 path $.e5e2c0ae-1257-4e0d-af77-5f3fd5b5b8bb.image
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at studio.metadata.DatabaseMetadataService.cleanUnofficialDatabase(DatabaseMetadataService.java:245)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:77)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 858 column 174891 path $.e5e2c0ae-1257-4e0d-af77-5f3fd5b5b8bb.image
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 17 more

**Desktop and environment (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by Sr31000** [comment] 2023-09-16 08:35
Même probléme

2023-09-16 10:34:58,537 [ERROR] [io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer] [VertxIsolatedDeployer.java:77]: Failed in deploying verticle
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 24 column 28685 path $.a7be0fff-55eb-4b11-9405-512fe69b7b7c.image
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at studio.metadata.DatabaseMetadataService.cleanUnofficialDatabase(DatabaseMetadataService.java:245)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:77)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 24 column 28685 path $.a7be0fff-55eb-4b11-9405-512fe69b7b7c.image
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 17 more

**Comment by MAcdugels** [comment] 2023-09-19 15:02
@Sr31000 tu as trouvé une solution ?

**Comment by Sr31000** [comment] 2023-09-19 16:54
Oui j'ai changé de PC 😅

**Comment by jeremysan** [comment] 2023-11-22 10:48
Bonjour,
pour ma part j'ai réussi à résoudre le problème en supprimant après les avoir sauvegardés les éléments présents dans le dossier mac user(Dossier de départ)/.studio/ et les studio-xxx.log dans le dossier user/
il doit y avoir le meme type de dossier sur windows.
j'ai relancé l'application et il n'y avait plus les packs d'histoire de la bibliothèque.
Je les ai recopié en ayant corrigé un pack qui s'était mal enregistré et auquel il n'y avait pas d'extension. j'ai mis l'extension .zip et maintenant tout remarche presque comme avant.

**Comment by marian-m12l** [comment] 2024-06-16 22:23
I'm closing issues from past years. Feel free to reopen if needed.

**Closed by marian-m12l** 2024-06-16 22:23 UTC
