### ISSUE TITLE
unable to launch sutdio on a Mac M1

### ISSUE THREAD

**Issue by MrAurik** [marian-m12l/studio#369] opened 2023-05-26 09:27 UTC
Hello.

I've Install JDK 20 on a MAC M1.
When I launch studio-macos.sh in the terminal I get this error :

```
2023-05-26 11:17:57,768 [ERROR] [i.v.c.i.l.c.VertxIsolatedDeployer]: Failed in deploying verticle
java.lang.ExceptionInInitializerError
	at studio.driver.LibUsbDetectionHelper.initializeLibUsb(LibUsbDetectionHelper.java:50)
	at studio.driver.raw.RawStoryTellerAsyncDriver.<init>(RawStoryTellerAsyncDriver.java:45)
	at studio.webui.service.StoryTellerService.<init>(StoryTellerService.java:54)
	at studio.webui.MainVerticle.start(MainVerticle.java:60)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.usb4java.LoaderException: Native library not found in classpath: /org/usb4java/darwin-aarch64/libusb4java.dylib
	at org.usb4java.Loader.extractLibrary(Loader.java:246)
	at org.usb4java.Loader.load(Loader.java:323)
	at org.usb4java.LibUsb.<clinit>(LibUsb.java:690)
	... 16 more
```

Did someone allready had this issue ?

Thanks in advance !

**Comment by tplet** [comment] 2023-07-06 19:44
Try this, but not waiting for any answer to resolve some error : https://github.com/marian-m12l/studio/issues/244

**Comment by MrAurik** [comment] 2023-07-07 07:02
> Try this, but wait for any answer to resolve some error : #244

Thanks, I will have a look :-)

**Comment by marian-m12l** [comment] 2024-06-16 23:03
Duplicate of #244

**Closed by marian-m12l** 2024-06-16 23:03 UTC
