### ISSUE TITLE
Can't launch studio-web-ui-0.3.1

### ISSUE THREAD

**Issue by JulS5931** [marian-m12l/studio#359] opened 2023-03-21 18:03 UTC
**Describe the bug**

**To Reproduce**
I installed the latest version of Java  :
 java -version                                                       
java version "20" 2023-03-21
Java(TM) SE Runtime Environment (build 20+36-2344)
Java HotSpot(TM) 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)

When I launch studio-macos.sh I have an error message and it quit

2023-03-21 19:02:20,156 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2023-03-21 19:02:20,158 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Registering hotplug listener
2023-03-21 19:02:20,159 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
java.lang.ExceptionInInitializerError
	at studio.driver.LibUsbDetectionHelper.initializeLibUsb(LibUsbDetectionHelper.java:50)
	at studio.driver.raw.RawStoryTellerAsyncDriver.<init>(RawStoryTellerAsyncDriver.java:45)
	at studio.webui.service.StoryTellerService.<init>(StoryTellerService.java:54)
	at studio.webui.MainVerticle.start(MainVerticle.java:60)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.usb4java.LoaderException: Native library not found in classpath: /org/usb4java/darwin-aarch64/libusb4java.dylib
	at org.usb4java.Loader.extractLibrary(Loader.java:246)
	at org.usb4java.Loader.load(Loader.java:323)
	at org.usb4java.LibUsb.<clinit>(LibUsb.java:690)
	... 16 more
2023-03-21 19:02:20,162 [ERROR] [i.v.c.i.l.c.VertxIsolatedDeployer]: Failed in deploying verticle
java.lang.ExceptionInInitializerError
	at studio.driver.LibUsbDetectionHelper.initializeLibUsb(LibUsbDetectionHelper.java:50)
	at studio.driver.raw.RawStoryTellerAsyncDriver.<init>(RawStoryTellerAsyncDriver.java:45)
	at studio.webui.service.StoryTellerService.<init>(StoryTellerService.java:54)
	at studio.webui.MainVerticle.start(MainVerticle.java:60)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.usb4java.LoaderException: Native library not found in classpath: /org/usb4java/darwin-aarch64/libusb4java.dylib
	at org.usb4java.Loader.extractLibrary(Loader.java:246)
	at org.usb4java.Loader.load(Loader.java:323)
	at org.usb4java.LibUsb.<clinit>(LibUsb.java:690)
	... 16 more
java.lang.ExceptionInInitializerError
	at studio.driver.LibUsbDetectionHelper.initializeLibUsb(LibUsbDetectionHelper.java:50)
	at studio.driver.raw.RawStoryTellerAsyncDriver.<init>(RawStoryTellerAsyncDriver.java:45)
	at studio.webui.service.StoryTellerService.<init>(StoryTellerService.java:54)
	at studio.webui.MainVerticle.start(MainVerticle.java:60)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.usb4java.LoaderException: Native library not found in classpath: /org/usb4java/darwin-aarch64/libusb4java.dylib
	at org.usb4java.Loader.extractLibrary(Loader.java:246)
	at org.usb4java.Loader.load(Loader.java:323)
	at org.usb4java.LibUsb.<clinit>(LibUsb.java:690)
	... 16 more

**Desktop and environment (please complete the following information):**
 - OS: MAC OS 13.2.1
 - Browser NA
 - Java version:  java version "20"
 - Maven version: [e.g. 3.6.0]
 - STUdio application version : studio-web-ui-0.3.1

Thanks for your help :)
Julien

**Comment by yukes33** [comment] 2023-03-31 19:14
Hello, 
I'm in the same situation as @JulS5931 
Thanks for the help @b3j0f. I have the docker running but nothing happens then. When going to localhost:8080, the host is unreachable.
Could you help me/us ?
Thanks

The log from docker is this :
2023-03-31 21:05:32 2023-03-31 19:05:32,909 [WARN ] [s.m.DatabaseMetadataService]: Missing official metadata database file
2023-03-31 21:05:32 java.io.FileNotFoundException: /root/.studio/db/official.json (No such file or directory)
2023-03-31 21:05:32     at java.base/java.io.FileInputStream.open0(Native Method)
2023-03-31 21:05:32     at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
2023-03-31 21:05:32     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
2023-03-31 21:05:32     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
2023-03-31 21:05:32     at java.base/java.io.FileReader.<init>(FileReader.java:60)
2023-03-31 21:05:32     at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:42)
2023-03-31 21:05:32     at studio.webui.MainVerticle.start(MainVerticle.java:47)
2023-03-31 21:05:32     at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
2023-03-31 21:05:32     at io.vertx.core.Verticle.start(Verticle.java:66)
2023-03-31 21:05:32     at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
2023-03-31 21:05:32     at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
2023-03-31 21:05:32     at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
2023-03-31 21:05:32     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
2023-03-31 21:05:32     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
2023-03-31 21:05:32     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
2023-03-31 21:05:32     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2023-03-31 21:05:32     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-03-31 21:05:32     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-03-31 21:05:32     at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-31 21:05:33 2023-03-31 19:05:33,954 [INFO ] [s.m.DatabaseMetadataService]: Fetched metadata, updating local database
2023-03-31 21:05:34 2023-03-31 19:05:34,067 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2023-03-31 21:05:34 2023-03-31 19:05:34,068 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Registering hotplug listener
2023-03-31 21:05:34 2023-03-31 19:05:34,069 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2023-03-31 21:05:34 2023-03-31 19:05:34,074 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is supported. Registering hotplug callback(s)...
2023-03-31 21:05:34 2023-03-31 19:05:34,074 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2023-03-31 21:05:34 2023-03-31 19:05:34,078 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Registering hotplug listener
2023-03-31 21:05:34 2023-03-31 19:05:34,078 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2023-03-31 21:05:34 2023-03-31 19:05:34,079 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is supported. Registering hotplug callback(s)...
2023-03-31 21:05:34 2023-03-31 19:05:34,079 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2023-03-31 21:05:34 2023-03-31 19:05:34,177 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2023-03-31 21:05:34 2023-03-31 19:05:34,191 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2023-03-31 21:09:20 2023-03-31T19:11:08.119191297Z 2023-03-31 19:11:08,118 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2023-03-31 21:11:08 2023-03-31 19:11:08,121 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Registering hotplug listener
2023-03-31 21:11:08 2023-03-31 19:11:08,122 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2023-03-31 21:11:08 2023-03-31 19:11:08,128 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is supported. Registering hotplug callback(s)...
2023-03-31 21:11:08 2023-03-31 19:11:08,128 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2023-03-31 21:11:08 2023-03-31 19:11:08,132 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Registering hotplug listener
2023-03-31 21:11:08 2023-03-31 19:11:08,132 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2023-03-31 21:11:08 2023-03-31 19:11:08,133 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is supported. Registering hotplug callback(s)...
2023-03-31 21:11:08 2023-03-31 19:11:08,134 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2023-03-31 21:11:08 2023-03-31 19:11:08,206 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2023-03-31 21:11:08 2023-03-31 19:11:08,224 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle

**Comment by JulS5931** [comment] 2023-04-01 13:41
Thanks @b3j0f 
After a few modifications, I managed to have the script running. But still no access to the UI interface. I tried localhost:8080 but it doesn't work. Here are the log from the terminal running : 

docker-compose run studio
[+] Running 1/0
 ⠿ Network studio_default  Created                                         0.0s
2023-04-01 13:39:28,445 [WARN ] [s.m.DatabaseMetadataService]: Missing official metadata database file
java.io.FileNotFoundException: /root/.studio/db/official.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at studio.metadata.DatabaseMetadataService.<init>(DatabaseMetadataService.java:42)
	at studio.webui.MainVerticle.start(MainVerticle.java:47)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-01 13:39:30,550 [INFO ] [s.m.DatabaseMetadataService]: Fetched metadata, updating local database
2023-04-01 13:39:30,665 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2023-04-01 13:39:30,666 [DEBUG] [s.d.r.RawStoryTellerAsyncDriver]: Registering hotplug listener
2023-04-01 13:39:30,667 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2023-04-01 13:39:30,671 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is supported. Registering hotplug callback(s)...
2023-04-01 13:39:30,671 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2023-04-01 13:39:30,674 [DEBUG] [s.d.f.FsStoryTellerAsyncDriver]: Registering hotplug listener
2023-04-01 13:39:30,674 [INFO ] [s.d.LibUsbDetectionHelper]: Initializing libusb...
2023-04-01 13:39:30,674 [INFO ] [s.d.LibUsbDetectionHelper]: Hotplug is supported. Registering hotplug callback(s)...
2023-04-01 13:39:30,675 [DEBUG] [s.d.LibUsbAsyncEventsWorker]: Starting worker thread to handle libusb async events...
2023-04-01 13:39:30,739 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2023-04-01 13:39:30,747 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle

**Comment by marian-m12l** [comment] 2024-06-16 23:04
Duplicate of #244

**Closed by marian-m12l** 2024-06-16 23:04 UTC
