### ISSUE TITLE
OSX fresh install, box not visible on web interface

### ISSUE THREAD

**Issue by ze6killer** [marian-m12l/studio#134] opened 2020-09-25 10:58 UTC
Hello, and first thanks for all your work.

Just did a fresh install on a Macbook pro, latest os and firefox updates.
Retrieved the database via the tocken through the curl command you suggested. So far so good.

Then when launching the studio.macos.sh I get the following output in the terminal and the Library section on the web interface is empty. The path indicated for the .studio folder is the correct one and/but when I go through the finder have a look at the .studio/library folder, I notice that it is empty.

Also the box is connected and correctly displays the USB symbol. If I launch the official lunii app, the box is detected correctly.
Hopefully I'm not just waisting your time because I somehow missed a step during install.

```
DarkBook:studio-web-ui-0.2.0 PTIM$ ./studio-macos.sh 
2020-09-25 12:43:29,103 [INFO ] [s.w.s.StoryTellerService]: Setting up story teller driver
2020-09-25 12:43:29,110 [INFO ] [s.d.LibUsbHelper]: Initializing libusb...
2020-09-25 12:43:29,122 [INFO ] [s.d.LibUsbHelper]: Hotplug is supported. Registering hotplug callback...
2020-09-25 12:43:29,231 [INFO ] [s.w.MainVerticle]: Opening URL in default browser...
2020-09-25 12:43:29,569 [INFO ] [i.v.c.i.l.c.VertxIsolatedDeployer]: Succeeded in deploying verticle
2020-09-25 12:43:30,582 [ERROR] [s.w.MainVerticle]: Exception thrown
java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:484)
	at java.base/sun.nio.ch.FileChannelImpl.transferToTrustedChannel(FileChannelImpl.java:595)
	at java.base/sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:688)
	at io.netty.channel.DefaultFileRegion.transferTo(DefaultFileRegion.java:130)
	at io.netty.channel.socket.nio.NioSocketChannel.doWriteFileRegion(NioSocketChannel.java:362)
	at io.netty.channel.nio.AbstractNioByteChannel.doWriteInternal(AbstractNioByteChannel.java:235)
	at io.netty.channel.nio.AbstractNioByteChannel.doWrite0(AbstractNioByteChannel.java:209)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:400)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:124)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:205)
	at io.vertx.core.http.impl.Http1xServerConnection.writeToChannel(Http1xServerConnection.java:267)
	at io.vertx.core.net.impl.ConnectionBase.sendFileRegion(ConnectionBase.java:417)
	at io.vertx.core.net.impl.ConnectionBase.sendFile(ConnectionBase.java:444)
	at io.vertx.core.http.impl.Http1xServerConnection.sendFile(Http1xServerConnection.java:456)
	at io.vertx.core.http.impl.HttpServerResponseImpl.doSendFile(HttpServerResponseImpl.java:514)
	at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:433)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:365)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:351)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendFile$11(StaticHandlerImpl.java:457)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.wrapInTCCLSwitch(StaticHandlerImpl.java:266)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.sendFile(StaticHandlerImpl.java:392)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$null$0(StaticHandlerImpl.java:231)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.getFileProps(StaticHandlerImpl.java:299)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:208)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by marian-m12l** [comment] 2020-09-28 11:41
Hi. You're probably running the new firmware, which is not supported, unfortunately.
As for the library, it is indeed *supposed* to be empty until you create a story pack.
Thanks for the feedback :+1:

**Comment by ze6killer** [comment] 2020-09-28 17:19
Hi,

Thanks for your quick response.
- New firmware -> damn ! Is it expected to be supported soon? Do you know
if I can downgrade?
- Library -> I thought I was supposed to be able to see the "official"
storied already loaded and that one part of the installation was aiming at
retrieving the images for those.

If there is anything I can test in order to help, let me know, I'll be glad
to.

Regards,
Ze

**Comment by marian-m12l** [comment] 2020-09-29 07:02
@ze6killer You can follow #122 for progress on the new firmware; although, if it was straightforward, it would already be supported.. I've not really looked into downgrading, but that looks unlikely. The json metadata you fetch during installation is indeed meant to retrieve images and pack names from the official library, but that's it, it's just used to display correctly the packs that you have on your device. The "local library" in STUdio holds your own story packs, that you can then (hopefully) transfer to the device.

**Comment by ze6killer** [comment] 2020-09-29 09:13
Hello,

Thanks for your reply.
I  re-read my previous message and must apologize if it sounded
reproachful, it was not my intent : of course, I can guess that if the
newest FW is not supported, there are some good reasons.
My "damn !" exclamantion was linked to the fact that I had upgraded the
firmware some 2 days before thinking it would solve the issue with the
library not being displayed :’D
In any case, I will follow #122, thanks for the link.

Regarding the contents of the library, this is not urgent and sorry if I’m
being a little thick but you wrote *"it's just used to display correctly
the packs that you have on your device"* so what I understand is that the
packs that were already on my device should have been displayed prior to
the firmware upgrade.
If this is correct, then my feedback to you is : I don’t think this was
working as expected (though now I cannot test again because of the firmware)
If this is not correct, then my feedback to you is : there might be some
other slow-minded persons like me out there who could benefit from an
explanation on this topic in your manual (nothing urgent though)

Hope this helps.
Ze

**Comment by marian-m12l** [comment] 2020-09-29 11:53
@ze6killer don't worry, I didn't take it as an offense :). Although I can see how my answer makes your think so. I was just expressing my disappointment regarding the slow progress on supporting the new firmware...
Regarding the pack metadata, yes, when the device is plugged, a panel is supposed to appear on the left of the UI and display the packs that are in the device, using "official" pack metadata. Some people seem to need to refresh the page for this panel to appear, although I cannot reproduce this behaviour.
Thanks for the feedback, it is really appreciated!

**Comment by marian-m12l** [comment] 2024-06-16 22:57
I'm closing issues from past years. Feel free to reopen if needed.

**Closed by marian-m12l** 2024-06-16 22:57 UTC
