### ISSUE TITLE
Freeze when reading audio

### ISSUE THREAD

**Issue by ex23** [marian-m12l/studio#162] opened 2021-01-15 13:58 UTC
**Describe the bug**
I generate a very simple pack (one start node + one story node) with STUdio 0.3.0-beta.1 and load it to my device. According to STUdio, everything seems to work fine.

But when I select this pack on my device by turning the wheel, the audio of the start node starts playing for a few seconds before freezing. At last the device reboots.

If I click on OK before it freezes, then I'm supposed to reach the story node. But instead I have an error screen (a picture inviting to connect the device to a computer + the text "ERROR") and have to reboot.

I get the exact same problem with the STUdio "Sample pack". So the problem doesn't seem to be caused somehow by the audio files I use.

**Screenshots**
![2021-01-15 14 49 14](https://user-images.githubusercontent.com/77390400/104734834-20388d80-5741-11eb-8136-bee9a1db2b2e.jpg)

**Logs**
[studio-latest.log](https://github.com/marian-m12l/studio/files/5820875/studio-latest.log)
[Console.txt](https://github.com/marian-m12l/studio/files/5820877/Console.txt)

**Desktop and environment (please complete the following information):**
 - OS: Windows 7 x64
 - Browser: Firefox
 - Java version: JDK 15.0.1 Windows x64
 - Maven version: Pas installé
 - STUdio application version 0.3.0-beta.1

**Comment by ex23** [comment] 2021-01-15 14:12
Let me add more details about this bug:

- I have also tested with Edge instead of Firefox: same problem.
- I have tested with multiple MP3 and OGG files from different sources: same problem.
- Somehow, with some MP3 files it doesn't freeze on the start node. I can also not put any audio file on my start node. In those cases, I have no problem with the start node.
- But whatever I do, it always crashes straight ahead on the story node, with the error picture shown above. It doesn't play for a few seconds before freezing, no. It doesn't play any audio and immediately displays the error picture.

**Comment by ex23** [comment] 2021-01-15 14:27
I think I understood the source of the problem. Actually, the answer was somewhat in the help of STUdio:

![2021-01-15 14 49 14](https://user-images.githubusercontent.com/77390400/104738226-86bfaa80-5745-11eb-9187-170815ece267.jpg)

I do not really understand why, but it's written, about the Story Node, that "**YOU SHOULD NOT HAVE A SINGLE STORY NODE RIGHT AFTER THE COVER NODE**".

Indeed, if I try to create a more complex story, it works ! The problem was that I was trying to create a too simple story with just one cover node + a story node. This is not accepted by the device and makes it crash.

I don't think it's really possible to fix this "bug" in STUdio because it is caused by the behavior of the device.

But it would be good if STUdio would check for this case and warn the user that the diagram is not valid.

**Comment by marian-m12l** [comment] 2021-01-15 21:01
@ex23 Thanks for the feedback!

This is odd. This limitation of the story node was not motivated by incompatibility with the device. It's that such a construct essentially traps you in your story pack with no way of going back and loading another story unless you power off the device.

But you say a more complex story packs works? With the same image/audio assets? That's something I'd like to understand.. could be that there's something off in the pack generation. Could also be something specific to V2 devices.

Would you be able you make and share with me (privately if needed) a minimal story pack that causes errors vs. a pack that works for you?

**Comment by lololitoto** [comment] 2021-01-15 22:56
Bonjour, un peu le meme probleme pour moi, j'ai telecharge quelques packs mais quand je les dépose sur la boite et que j'essaye de les lire ca fait bugger, ca freeze et ca redemarre... je n'ai pas réussi à en lire une pour le moment...

merci beaucoup pour ce superbe boulot!

**Comment by marian-m12l** [comment] 2021-01-15 23:00
@lololitoto pour identifier la source du problème, le mieux serait de construire un pack minimal qui pose problème, et voir quels changements le font fonctionner (et inversement). Je n'ai pas encore testé sur l'appareil, mais la denière nightly devrait améliorer l'encodage mp3.

**Comment by marian-m12l** [comment] 2021-01-15 23:07
@lololitoto sur quelle version de la lunii ?

**Comment by lololitoto** [comment] 2021-01-15 23:09
Version firmware : 2.20
même l'histoire simplified sample freeze en fait

**Comment by marian-m12l** [comment] 2021-01-15 23:10
Donc une version "made in france". Visiblement il reste quelque chose à régler. Est-ce que la dernière nightly aide ?

**Comment by lololitoto** [comment] 2021-01-15 23:12
oui made in france! désolé mais elle est où la dernière version?

**Comment by marian-m12l** [comment] 2021-01-15 23:14
https://github.com/marian-m12l/studio/actions/runs/489078208 (le lien "artifact" contient l'archive)

**Comment by lololitoto** [comment] 2021-01-15 23:30
ok j'ai essayé et ca fait pareil

en fait je viens de tester sur une histoire le lyon et la souris et je me rends compte que je peux "sauter" l'image de couverture et que ca ne freeze pas en revanche ca freeze apres le texte derriere

**Comment by Hybris03** [comment] 2021-01-16 10:26
Bonjour à tous,
Tout d'abord merci beaucoup pour le travail effectué :)
je viens de tester avec studio 0.3.0-beta.1 et je rencontre le même problème.
Ma lunii est une V2 en firmware 2.20.
Dès que je vais sur l'histoire, ça se fige et ça reboot.
Quand je vais sur l'histoire mais je que clique sur le bouton "OK" avant que la lunii ait dit le nom de l'histoire, ça passe à l'étape suivante mais l'image ne s'affiche pas et la lunii reboot aussi.
Je suis le fil et je test avec les différentes versions en attendant qu'une solution soit trouvée.

**Comment by Titou472** [comment] 2021-01-16 16:03
> Bonjour à tous,
> Tout d'abord merci beaucoup pour le travail effectué :)
> je viens de tester avec studio 0.3.0-beta.1 et je rencontre le même problème.
> Ma lunii est une V2 en firmware 2.20.
> Dès que je vais sur l'histoire, ça se fige et ça reboot.
> Quand je vais sur l'histoire mais je que clique sur le bouton "OK" avant que la lunii ait dit le nom de l'histoire, ça passe à l'étape suivante mais l'image ne s'affiche pas et la lunii reboot aussi.
> Je suis le fil et je test avec les différentes versions en attendant qu'une solution soit trouvée.

Bonjour tout le monde!
Je me lance aussi dans l'aventure, merci marian pour le travail de titan que tu réalises!
J'ai exactement le même problème que ceux évoqués, testé avec plusieurs packs différents , l'image s'affiche puis ça freeze.
Dernière Beta studio et Lunii V2 en Fw 2.20

**Comment by marian-m12l** [comment] 2021-01-16 22:00
Merci pour les retours. Visiblement la V2 est plus exigeante :-)

Je viens de pousser un correctif, les dernières "frames" des MP3 générés pouvaient être incomplètes/corrompues, ce qui collerait à la description du problème (crash en fin de lecture). Dites-moi ce que ça donne sur vos V2 : https://github.com/marian-m12l/studio/actions/runs/490662555

**Comment by laurenth44** [comment] 2021-01-16 22:58
Bonsoir Marian, je viens de t'envoyer un mail, mais je pousse aussi l'info ici : Ca marche !! J'ai pour l'instant testé uniquement un pack qui ne fonctionnait pas, et qui fonctionne maintenant, je vais tester les autres.

**Comment by thi71126** [comment] 2021-01-16 23:00
Super boulot, t'es un génie!

j'étais justement en train de constater le problème et de voir le post sur le sujet que tu publies le correctif dans la foulée.
trés bon timing pour moi ;)

je confirme que l'import des pack qu'on peut trouver par ci par là semble fonctionner.
j'en ai testé 2 et j'ai pas eu de problème

par contre j'étais en train de tester la création d'un pack et il ne fonctionne pas même en repartant de zéro
avec la version précédente ca plantait dans le "Menu node" pendant la transition entre la "question" et les "options"
maintenant ca plante dès le "Cover node" quand j'arrive sur mon histoire => pas de son pas d'image => reboot
j'ai créé juste une histoire de test avec 2 options et 2 histoire avec des mp3 trouvé sur internet.

Bonne continuation

**Comment by lololitoto** [comment] 2021-01-16 23:01
Marian ca a l'air de fonctionner en tout cas j'ai testé sur 3 packs et ca fonctionne alors que ca ne fonctionnait pas. Merci beaucoup t'es au top!!!

j'ai trouvé un pack qui ne fonctionne pas et j'ai beau l'ouvrir je ne vois pas le souci...
je peux te le deposer pour que tu vois si tu le souhaites

**Comment by lololitoto** [comment] 2021-01-16 23:05
[lecoledesloisirs_V2_test-62a33a47-e7ab-4617-b9dc-38fbc88e97d5-v2.zip](https://github.com/marian-m12l/studio/files/5825257/lecoledesloisirs_V2_test-62a33a47-e7ab-4617-b9dc-38fbc88e97d5-v2.zip)

c'est celui là, en fait ca ne freeze pas mais l'histoire ne démarre pas, on peut revenir en arriere par contre... je comprends pas bien pourquoi

**Comment by marian-m12l** [comment] 2021-01-17 20:48
Merci pour les retours. On a fait un pas en avant :-)

@thi71126 Il faudrait voir l'encodage des MP3

@lololitoto visiblement les MP3 des histoires sont déjà en mono/44100Hz, donc il n'y a pas de ré-encodage. Quelques différences qui pourraient ne pas plaire à la lunii: les fichiers contiennent des "tags" ID3 et lame et le bitrate est constant (64kbps)

**Comment by FabienSerny** [comment] 2021-01-17 21:26
Tout d'abord, merci pour **l'énorme** travail effectué sur cette application :)

J'ai le même soucis que les personnes au dessus, je rajoute les infos si ça peut aider cerner le soucis.
Je ne pense que cela vienne de l'encodage du mp3.

J'utilise 0.3.0-beta.2-SNAPSHOT et la version firmware de la Lunii est 2.6
J'ai fait un test avec une chanson, j'arrive à uploader le pack et la couverture se lance.
La couverture contient une version cut de la musique et elle se lit parfaitement.
C'est seulement lorsque je clique sur "OK" que j'obtiens l'erreur.

![IMG_4226](https://user-images.githubusercontent.com/1514353/104856382-b1ab2980-5912-11eb-9e94-90a2d624e745.jpeg)
![IMG_4227](https://user-images.githubusercontent.com/1514353/104856384-b4a61a00-5912-11eb-83a7-c89e1b112428.jpeg)

Je peux me tromper mais si c'était un soucis d'encodage de musique, j'aurai le soucis dès la couverture, qu'en pensez vous ?

Le zip posant soucis : 
[Pour_louper_lecole-01fc131c-f7d4-4a88-9d6b-bca29b7ae566-v1.zip](https://github.com/marian-m12l/studio/files/5826867/Pour_louper_lecole-01fc131c-f7d4-4a88-9d6b-bca29b7ae566-v1.zip)

Encore merci pour le travail fourni sur ce soft !

**Comment by lololitoto** [comment] 2021-01-18 09:08
> @lololitoto visiblement les MP3 des histoires sont déjà en mono/44100Hz, donc il n'y a pas de ré-encodage. Quelques différences qui pourraient ne pas plaire à la lunii: les fichiers contiennent des "tags" ID3 et lame et le bitrate est constant (64kbps)

**Comment by ex23** [comment] 2021-01-18 15:24
@marian-m12l J'ai testé ta dernière Nightly Build (0.3.0-beta.2-SNAPSHOT). Pour moi ça ne change rien aux problèmes.

[Test6-301f3721-f3f6-4d48-ba00-310fe23de4fa-v1.zip](https://github.com/marian-m12l/studio/files/5830904/Test6-301f3721-f3f6-4d48-ba00-310fe23de4fa-v1.zip)
[Test6bis-9b9e2b56-462e-4429-b0e0-3e66c783fcc4-v1.zip](https://github.com/marian-m12l/studio/files/5830905/Test6bis-9b9e2b56-462e-4429-b0e0-3e66c783fcc4-v1.zip)
[Test7bis-74de4953-3c79-45af-8fae-1c88b53ba31f-v1.zip](https://github.com/marian-m12l/studio/files/5830906/Test7bis-74de4953-3c79-45af-8fae-1c88b53ba31f-v1.zip)
[Test7-cb06f420-e701-40dd-88ee-9f6d1f40d802-v1.zip](https://github.com/marian-m12l/studio/files/5830908/Test7-cb06f420-e701-40dd-88ee-9f6d1f40d802-v1.zip)

Voici 4 packs minimalistes permettant de reproduire les problèmes que je rencontre. Le pack Test6 contient juste un noeud de couverture + un noeud histoire. Je rencontre deux problèmes avec ce pack. Si je reste sur le noeud de couverture, la Lunii plante à la fin de la lecture audio (tactacatac puis reboot). Mais si j'appuie sur OK avant le plantage, à la place du noeud histoire j'ai l'image d'erreur.
![image](https://user-images.githubusercontent.com/77390400/104930212-2464e500-59a5-11eb-93e9-76ef9131521a.png)

Le pack Test7 est le même que le Test6 (mêmes fichiers MP3), sauf que j'y ai rajouté un noeud menu. Le noeud de couverture plante de la même façon que pour le pack Test6 à la fin de la lecture. Par contre le noeud menu et le noeud histoire (pourtant identique à celui du Test6) démarre bien. Cependant à la fin du fichier audio du noeud histoire ça plante de nouveau.
![image](https://user-images.githubusercontent.com/77390400/104930796-eae0a980-59a5-11eb-8029-dbaf78c1e32d.png)

Les packs Test6bis et Test7bis sont les mêmes que respectivement les Test6 et Test7 mais sans fichier audio sur le noeud de couverture, permettant d'éliminer le plantage sur ces noeuds.

J'en conclus qu'il y a deux problèmes qui semblent indépendants:

1. Un pack minimaliste contenant juste un noeud couverture + un noeud histoire ne fonctionne pas (jolie image ERROR). Ce n'est pas très grave puisque le problème est facilement contournable en complexifiant un peu le pack. Si ce problème est confirmé et reproductible chez les autres, je pense qu'il faudrait que STUdio avertisse l'utilisateur qu'un tel diagramme n'est pas valide.

2. La Lunii plante à la fin de la lecture des fichiers audio. Chez moi le problème semble généralisé à tous les fichiers audio. J'ai testé différents MP3 et OGG provenant de différentes sources, j'ai tenté de les ré-encoder avec ffmpeg avant importation dans STUdio, j'ai tenté de supprimer tous les tags ID3 mais rien n'y fait, la Lunii plante systématiquement à la fin de la lecture.

Bon courage et merci !

**Comment by laurenth44** [comment] 2021-01-18 16:04
Bonjour ex23, je viens de tester tes packs, sur une V2 en 2.20, aucun
problème de mon côté. je pense que tu n'as pas récupéré la toute dernière
build.

J'ai testé uniquement Test7, tout fonctionne as expected, pas de plantage.

Voici pour rappel le lien direct pour télécharger la dernière version :
https://github.com/marian-m12l/studio/suites/1842938825/artifacts/35674873

le run (il faut dans ce cas cliquer sur le lien "artifact" :
https://github.com/marian-m12l/studio/actions/runs/490662555

Dans artifact.zip, vous avez la dernière build.

Cordialement,
Laurent

**Comment by thi71126** [comment] 2021-01-18 19:11
@ex23 Test6 est trop court, j'ai moi aussi eu des erreurs sans utilisation de "Menu node"
et test7 fonctionne aussi bien chez moi env 2.2

@marian-m12l j'ai compris pourquoi ça plantait chez moi! 
j’étais trop focalisé sur le son, j'avais essayé plein d'extension différentes mais rien ne fonctionnait. 
En fait le problème venait de l'image qui était trop lourde! je pensait que toutes les images fonctionnaient car dans le simulateur c'est nickel, ça adapte l'image au contenu. par contre une fois publié l'image n'est pas redimensionné.
![image](https://user-images.githubusercontent.com/77553154/104954736-19bc4700-59c9-11eb-9cfc-9f2c4d7d90ab.jpg)
c'est dommage ça ferait gagner du temps ;) 

A bientôt

**Comment by ex23** [comment] 2021-01-19 07:53
@laurenth44 Tu as raison. Je n'avais pas récupéré la dernière version ! Les tests de mon derniers message ont été réalisés sur la Nightly Build # 21.

Je viens de tester avec la Nightly Build # 22. Ca règle mon plus gros problème ! Je n'ai plus le problème de plantage en fin de lecture du fichier audio. Merci @marian-m12l !

Par contre, sur ma Lunii V2, le problème avec les packs simplissimes 1 noeud couverture + 1 noeud histoire est toujours là. Mais ce n'est pas très grave, il suffit de créer des packs un peu plus complexes.

**Comment by laurenth44** [comment] 2021-01-19 09:05
It's not a bug, it's a feature 😁

La lunii fonctionne ainsi, il lui faut les 3 niveaux, on ne peut pas
changer cette contrainte.

**Comment by ex23** [comment] 2021-01-19 09:09
Oui c'est ce que je comprends. Ce n'est pas grave. Ce qui est juste un peu dommage c'est que STUdio dit qu'un tel diagramme est valide. Sinon, il suffit de le savoir !

A part ça, tout fonctionne nickel maintenant.

**Comment by lololitoto** [comment] 2021-01-19 10:53
> @lololitoto visiblement les MP3 des histoires sont déjà en mono/44100Hz, donc il n'y a pas de ré-encodage. Quelques différences qui pourraient ne pas plaire à la lunii: les fichiers contiennent des "tags" ID3 et lame et le bitrate est constant (64kbps)

Problème réglé, j'ai enlevé les tags et remis les MP3, et ca fonctionne Nickel!

merci beaucoup t'es au top!

**Comment by FabienSerny** [comment] 2021-01-20 01:09
Je viens de tester la solution de @ex23 https://github.com/marian-m12l/studio/issues/162#issuecomment-762317395
Et en effet, si une histoire ne contient qu'un noeud ça plante, si on met un menu intérmediaire ça fonctionne \o/

Merci pour l'aide.

Et encore merci à @marian-m12l pour le travail incroyable fait sur cette app :)

**Comment by marian-m12l** [comment] 2021-01-22 23:06
Je viens de publier une nouvelle beta avec quelques correctifs: https://github.com/marian-m12l/studio/releases/tag/0.3.0-beta.2

En particulier pour corriger l'encodage MP3 et supprimer les tags ID3. Il y a aussi des vérifications supplémentaires sur les dimensions des images et la validation du graphe.

**Comment by marian-m12l** [comment] 2024-06-16 22:55
I'm closing issues from past years. Feel free to reopen if needed.

**Closed by marian-m12l** 2024-06-16 22:55 UTC
