### ISSUE TITLE
failed to check device

### ISSUE THREAD

**Issue by Lorenzinaccio** [marian-m12l/studio#121] opened 2020-06-30 18:24 UTC
![Screen Shot 2020-06-30 at 20 23 05](https://user-images.githubusercontent.com/65119711/86162803-abd52e80-bb0f-11ea-951f-273756b2d7a2.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Check the logs **in the console** for errors, if any. Join the `studio-latest.log` file if relevant.
Also check **the network tab of your browser's developer tools** and look for HTTP calls in error, if any. HTTP responses may contain useful data.

> Internal Server Error: Error 500: Internal Server Error	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 0.2.0

**Additional context**

**Comment by marian-m12l** [comment] 2020-07-01 11:05
Hi, thanks for the feedback. It looks like the same problem as #120, is it? Except you also have another process already binding on port 8080, you'll need to stop it before you run STUdio.

**Comment by Lorenzinaccio** [comment] 2020-07-01 17:20
Thanks a lot Marian, I try to check again tonight.Best.Crescendo fxVideo ExpertsLe 1 juil. 2020 13:05, marian-m12l <notifications@github.com> a écrit :
Hi, thanks for the feedback. It looks like the same problem as #120, is it? Except you also have another process already binding on port 8080, you'll need to stop it before you run STUdio.

**Comment by Lorenzinaccio** [comment] 2020-07-02 13:15
Hi Mariam,
I am sorry to disturb again but I tried to restart everything and still have the same error message . Maybe I should restart the lunii within the application. I am afraid to loose everything and not be able to link it to the STudio ?
Thanks for your amazing job;)
Laurent

**Comment by Lorenzinaccio** [comment] 2020-07-02 13:19
Here is the terminal window,
it’s green until I plug the lunii ??
In case you have any issue;)
Thanks again;)

**Comment by Lorenzinaccio** [comment] 2020-07-03 20:02
![Screen Shot 2020-07-02 at 15 17 54](https://user-images.githubusercontent.com/65119711/86495264-e988c000-bd78-11ea-96c2-09adff2c50af.png)

**Comment by marian-m12l** [comment] 2020-07-03 20:47
Hi @Lorenzinaccio 

Thanks for all the feedback.

This is definitely a duplicate of #120 

This seems to be related to a bug in libusb on earlier macOS versions (< 10.14) : see https://github.com/usb4java/usb4java/issues/78 and https://github.com/libusb/libusb/issues/519

The issue seems to be fixed with the latest release of libusb (1.0.23), unfortunately the Java wrapper has not been upgraded yet. If you're willing to experiment, you could try dropping the latest library in-place within `libusb4java-1.3.0-darwin-x86-64.jar`, but I'm not sure the libusb api is backwards-compatible. Otherwise, as the bugs seems to occur only when compiling on macOS 10.14+, maybe you could just recompile version 1.0.22 yourself.

**Comment by marian-m12l** [comment] 2024-06-16 22:58
I'm closing issues from past years. Feel free to reopen if needed.

**Closed by marian-m12l** 2024-06-16 22:58 UTC
