### ISSUE TITLE
"Home Button" inconstant behavior ?

### ISSUE THREAD

**Issue by Shasdo** [marian-m12l/studio#57] opened 2020-04-18 20:26 UTC
In the "Simplified Sample Pack" while in the Story node, pressing the home button get you to first menu node, and then pressing it again get you to the cover node.

I made a simple story.
Cover node -> Story node
Pressing the home button does nothing.

While playing a bit with it, I found a workaround.
It is to turn on the "Customize Home Transition Button" even if it is not connected to anything. (see picture)
![image](https://user-images.githubusercontent.com/4083901/79670407-01619680-81c3-11ea-98d9-d5d569762327.png)

Is it the intended behavior?
If so, maybe the "Customize Home Transition Button" label needs to be clarified.

Best regards.

**Comment by Shasdo** [comment] 2020-04-18 21:07
After reloading the pack in STUdio the Home Button  in the stoy node is not selected anymore.
Also, on the Lunii, after the story is finished, it directly restart the story node audio file.

PS:
You said that you did not want us to open the official pack in the editor and I am alright with it. But could you share pictures of how the more evolved stories are structured until an "Advanced Sample Pack" is created ?
Also, have you considered developping your software for an open source hardware?

Best regards.

**Comment by marian-m12l** [comment] 2020-04-19 19:57
Hi,

Some behaviours should be clarified in the documentation, I agree.
Regarding the HOME button, I need to clarify two things: how the Lunii plays a transition, and how STUdio sets transitions.

On the Lunii, things are pretty straightforward:
- If the HOME transition is set (with a link to another node), then it is followed (as expected)
- If the transition is **not** set (`-1` / `0xff` on the official/binary format, which translates to `null` on the archive/json format), this is interpreted as "go back to the first node / cover node"

If you are using Stage Nodes on STUdio, this is what you'll get. However, the so-called "simplified nodes" exist to easily mimick the behaviour you're getting on official packs. Therefore, they implement a **default behaviour** that is not visible on the graph:
- A Cover Node disables the HOME button altogether
- A Story Node actually **sets the HOME transition** to link to the "first useful node", which is the node directly following the cover
- A Menu Node actually generates several stage nodes. The HOME button is disabled during the question, and enabled on all options. On the options, STUdio tries to link to the "previous node", if only one node leads to this menu, in which case it **sets the transition**. If a single "previous node" cannot be found, the **transition is not set** which means "go back to the first node / cover node".

Pretty convoluted indeed. Maybe this should be improved.

Back to the Story Node, when you check "Customize Home Transition Button", you actually **override this default behaviour**. Which might be a better label for the button, btw.

As for your simple story, I think this is a case that is not handled correctly. The "first useful node" to which it links by default (when pressing HOME or when reaching the end of the audio file) is... itself.


P.S.: It's not that I don't want people to peek into official packs, but I don't want to make copying official packs easier. However, if you're compiling the application yourself, there's actually an "expert nodes" sample pack from before I added the simplified nodes. You'd need to replace the call to `simplifiedSample()` with a call to `sample()` (hopefully the sample is still working). Also, what open hardware do you have in mind? I'd be open to supporting more devices, either in the app or in a fork (I'm actually modifying the app locally to support a custom arduino-based player of mine).

Thanks for the feedback.

**Comment by marian-m12l** [comment] 2020-04-19 20:51
> After reloading the pack in STUdio the Home Button in the story node is not selected anymore.

Hopefully fixed on `master`. Empty "custom transitions" were ignored on story nodes.
Also on `master`, I changed to story nodes behaviour to go back to the cover node instead of the "first useful node" if the story node is the first node following the cover.

**Comment by Shasdo** [comment] 2020-04-20 17:33
Hello,

Thanks for you answer and your time.

I am using the windows version and unfortunatly I don't think I am capable of compiling a software. So that's why I was asking for a screenshot of the Advanced sample pack, just to have a look of how it is supposed to be arranged together. personally I don't care about official packs in STUdio, there is loads of podcasts that I can add to the lunii.

Anyway, as I understand it, it is not possible at the moment to make a simple story as described in my first picture?
If not, maybe it should, so it wloud allow us to make "quick & dirty" packs with one long story for example

I have tried to do it with the advanced nodes and it looked like that:
![STUDio bug2](https://user-images.githubusercontent.com/4083901/79779091-0f85f300-833a-11ea-9bc0-e0088799b8bc.png)
The check option validated the diagram. The preview in STUdio works fine and a press on the home button return you to the first Stage node

But once loaded on the Lunii it doesn't work correctly:
The first stage node worked but after pressing OK the screen turns off as it is supposed to, but the story doesn't start and now the Lunii is stuck. The home button is not responding.
I must turn it off and on to get back to the main menu.
Can you explain what's wrong with my method?
Maybe I should forget making a simple pack "Menu -> story" ?

About the open source hardware, I didn't have anything particular in mind, but I thought it would be a stronger project if it allows non proprietary devices. 
It would give it even more legitimacy regarding legal/moral issue with Lunii.
Anyway, arduino is cheap and easy to obtain, so it is nice to hear that you are working on this!

**Comment by marian-m12l** [comment] 2020-04-20 19:10
Hi,

I'll need to take more time to make this kind of story work properly. The fix I tried to make yesterday does not play well on the Lunii.

The issue is two-fold:
- Using a Story Node (or a Stage Node fwiw), the HOME button can go back to the cover node easily by having an empty transition, but the OK button / Autoplay transition **cannot** be null. So the OK transition must link to an Action Node, which in turn links to the Cover Node's FROM port (which does not exist today on the simplified cover node...)
- When using Action and Stage Nodes, your approach looks correct, however I think the issue is with the "flags": I think your "story" node **must** have an OK transition for the Lunii to play it (this is hidden when using simplified nodes), so you should enable either Autoplay or OK. In the sample pack, a story node would generally have these flags enabled: Home, Pause and Autoplay.

I'll check the diagram verification routine to make sure it reports an empty OK transition. For the Story Node (or any other OK transition) to link back to the cover node, I'll need to add an action somehow. It'll take a bit more time to figure out the good way to support this without breaking existing story packs.

**Comment by marian-m12l** [comment] 2020-04-20 19:14
Here's a screenshot of the "expert nodes" sample pack:

![SamplePackExpertNodes](https://user-images.githubusercontent.com/50991156/79790380-ecfcd580-834b-11ea-8755-ce42d16c6f1d.png)

**Comment by marian-m12l** [comment] 2020-04-20 19:22
And the pack file.

[SamplePackExpertNodes-ff31675f-f034-416d-9350-5042b504afff-v1.zip](https://github.com/marian-m12l/studio/files/4505660/SamplePackExpertNodes-ff31675f-f034-416d-9350-5042b504afff-v1.zip)

**Comment by Shasdo** [comment] 2020-04-20 21:28
Thanks again!

The pack helps a lot to wrap my head around how it is supposed to work.
It is a bit counteruntuitive at first and I understand how you felt the need to create simplified node.
It makes the edition of simple pack like "Title->Story Selection->Story playing" much more understandable.

FYI, the diagram verification in the Expert Sample Pack throw an error on the first node. It was a relief since I had one while playing around with expert node without understanding why.
![STUDio bug5](https://user-images.githubusercontent.com/4083901/79800348-584ea380-835c-11ea-960c-a87398b25dff.png)

Also, I have little suggestions to improve lisibility. I put them here but if you prefer I can open a new issue:
- The output icon with "Enable autoplay" or "Allow OK button" should reflect the choice and autoplay icon should have priority when both are enabled so you will directly see that this node doesn't require necesserly an action.
![Nintendo_code](https://user-images.githubusercontent.com/4083901/79800393-6c92a080-835c-11ea-970c-56aa51864c9e.png)

- An highligthing of the Input/Ouput Node when a link is selected would help with crowded "Action node"'. Behold the shameless paint edit
![STUDio bug4](https://user-images.githubusercontent.com/4083901/79800625-d8750900-835c-11ea-8acb-897f0bf235cb.png)
Or an highlighting + enlargement of both arrows of the link

Thanks for your time, je vais te laisser tranquille à présent ;-)

Nice work again!

**Comment by marian-m12l** [comment] 2020-04-21 18:53
Thanks for the suggestions, looks like nice improvements to do indeed. I'll track them in separate issues for better readability.

Regarding the error on the "expert nodes" sample, I figure it's the empty "from" port? I'll change this verification for the first node since I'm probably adding it to cover nodes and there's no need to check it since the first node is always reachable.

Thanks for the feedback, greatly appreciated!
Et il ne faut pas hésiter s'il y a d'autres problèmes ou améliorations à faire :-)

**Closed** 2020-05-02 14:08 UTC
