### ISSUE TITLE
character font

### ISSUE THREAD

**Issue by T1nd4** [marian-m12l/studio#38] opened 2020-03-09 21:49 UTC
Hi,

I have problems displaying accents.
When webserv shows my official packs, named are broken.
ex : 
- SorciÃ¨res  (Sorcières)
- Lâ€™Anniversaire volÃ© (L'anniversaire volé)

Thanks

**Comment by marian-m12l** [comment] 2020-04-01 11:40
Hi,

Thanks for the feedback! Is this the same as #29 ?

**Comment by T1nd4** [comment] 2020-04-01 17:20
Hi,
I think we all have the same prob.

**Comment by marian-m12l** [comment] 2020-04-02 19:44
Duplicate of #29

**Closed by marian-m12l** 2020-04-02 19:44 UTC
