### ISSUE TITLE
Can't save or export story pack

### ISSUE THREAD

**Issue by thekyz** [marian-m12l/studio#67] opened 2020-04-23 21:29 UTC
**Describe the bug**
If I click on "export" or "save" in the edit view, I get errors. This happens even with the example story pack.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Pack editor'
2. Click on 'Save pack to library'

**Expected behavior**
Being able to save I guess

**Screenshots**
![Screenshot 2020-04-23 at 23 24 39](https://user-images.githubusercontent.com/118808/80151238-fee3b000-85b9-11ea-9ff1-f8bf1ccc1773.png)
![Screenshot 2020-04-23 at 23 27 51](https://user-images.githubusercontent.com/118808/80151281-115de980-85ba-11ea-9d80-0205b0d87cff.png)

**Logs**
Browser console extract:
```
failed to export story pack 
TypeError
​columnNumber: 109262
​fileName: "http://localhost:8080/static/js/main.53727b63.chunk.js"
​lineNumber: 1
​message: "A.getNodes(...).filter(...).flatMap is not a function"
​stack: "e/<@http://localhost:8080/static/js/main.53727b63.chunk.js:1:109262\nc@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:657736\nu/o._invoke</<@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:657526\n_/</e[t]@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:658155\nr@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:93969\ns@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:94175\ni/</<@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:94234\ni/<@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:94116\ncA@http://localhost:8080/static/js/main.53727b63.chunk.js:1:108713\nA/t.exportPack@http://localhost:8080/static/js/main.53727b63.chunk.js:1:116586\np/<@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:514028\np@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:513950\nS/<@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:514704\nS@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:514673\nO@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:515231\nk@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:515041\nA@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:516131\nNn@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:543554\nPs@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:611945\nRe@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:523411\nOn@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:544035\nIs/<@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:612222\nt.unstable_runWithPriority@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:622566\nIs@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:612145\nMn@http://localhost:8080/static/js/2.391e29f6.chunk.js:1:543777\n"
​__proto__: {…}
​​constructor: function TypeError()
​​message: ""
​​name: "TypeError"
​​stack: ""
​​__proto__: Object { … }
> A.getNodes(...).filter(...).flatMap is not a function
```

**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:60.0) Gecko/20100101 Firefox/60.0
 - Java version:
```
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```
 - Maven version:
```
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 13.0.2, vendor: N/A, runtime: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
Default locale: en_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```
 - STUdio application version: 0.1.14-SNAPSHOT

**Additional context**
Pack library is connected and working fine, it shows my current library without issue, although I can't seem to export data from the Lunii.

![Screenshot 2020-04-23 at 23 29 20](https://user-images.githubusercontent.com/118808/80151396-4702d280-85ba-11ea-892b-095fba159b20.png)

**Comment by thekyz** [comment] 2020-04-23 21:31
Forgot to add that the logs from the app (studio-latest.log) does not show any significant data other than USB related messages.

**Comment by thekyz** [comment] 2020-04-24 07:45
After a bit of research I noticed that this happens only in Firefox, saving and exporting works fine in Chrome.

**Comment by marian-m12l** [comment] 2020-04-24 11:45
I'll have a look.
However I see you're using the latest version from `master`. I tried to fix an issue with story nodes but I messed up the pack saving, which may be the problem here.

**Comment by marian-m12l** [comment] 2020-05-02 14:07
Closing this issue as it was probably caused by my messing up of master.
Feel free to re-open if the problem comes back.

**Closed by marian-m12l** 2020-05-02 14:07 UTC
