### ISSUE TITLE
Compile error : Error resolving version for maven plugin

### ISSUE THREAD

**Issue by jin146** [marian-m12l/studio#46] opened 2020-04-03 11:02 UTC
Hi, 

I'm currently trying to install STUdio on a new linux machine.
I'm using these versions of maven and Java 
```
mvn --versionApache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/apache-maven-3.6.3
Java version: 11.0.5, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-173-lowlatency", arch: "amd64", family: "unix"
```
Here is the output of `mvn clean install`
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for studio:studio-agent:jar:0.1.12-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 55, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for studio:studio-core:jar:0.1.12-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for org.xiph:vorbis-java:jar should not point at files within the project directory, ${project.basedir}/../libs/vorbis-java-1.0.0-beta.jar will be unresolvable by dependent projects @ line 57, column 25
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for studio:studio-metadata:jar:0.1.12-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 31, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] studio-parent                                                      [pom]
[INFO] studio-metadata                                                    [jar]
[INFO] studio-agent                                                       [jar]
[INFO] studio-core                                                        [jar]
[INFO] studio-web-ui                                                      [jar]
[INFO] 
[INFO] ------------------------< studio:studio-parent >------------------------
[INFO] Building studio-parent 0.1.12-SNAPSHOT                             [1/5]
[INFO] --------------------------------[ pom ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/maven-metadata.xml
[WARNING] Could not transfer metadata org.apache.maven.plugins:maven-compiler-plugin/maven-metadata.xml from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/maven-metadata.xml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for studio-parent 0.1.12-SNAPSHOT:
[INFO] 
[INFO] studio-parent ...................................... FAILURE [  1.779 s]
[INFO] studio-metadata .................................... SKIPPED
[INFO] studio-agent ....................................... SKIPPED
[INFO] studio-core ........................................ SKIPPED
[INFO] studio-web-ui ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.675 s
[INFO] Finished at: 2020-04-03T12:57:55+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Error resolving version for plugin 'org.apache.maven.plugins:maven-compiler-plugin' from the repositories [local (/home/pikachu/.m2/repository), central (https://repo.maven.apache.org/maven2)]: Plugin not found in any plugin repository -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginVersionResolutionException

```

**Comment by marian-m12l** [comment] 2020-04-03 11:50
Hi,

Thanks for the feedback, but I could not reproduce. WHat's strange is that I don't specify a particular version of maven-compiler-plugin. Also, I have no problem downloading the metadata from the given url (https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/maven-metadata.xml). Maybe this was just a glitch with maven central? Or could there be a problem in your maven installation?

**Comment by jin146** [comment] 2020-04-03 12:51
I'll try again to check if there's an issue with maven's repo.

I first installed maven with apt-get command, wich took version 3.3 from my distro's repository. Then, I tried the latest binary from maven's website and installed it with the following command : 
`export PATH=/usr/local/apache-maven-3.6.3/bin:$PATH`

How could I check if the installation is good ?

**Comment by marian-m12l** [comment] 2020-04-09 20:08
Any progress?

**Comment by jin146** [comment] 2020-04-09 20:32
I was much more dedicated to creating story packs with your great software !
By the more, I'm a complete beginner in compiling : all I can do is to copy-paste commands and search for missing libraries, It will take some time searching for such a project to compile.
As a workaround, I thought I could try compiling on another machine I happen to have saved from the attic's dust yesterday, I installed antiX on it wich is based on Debian10.

**Comment by marian-m12l** [comment] 2020-04-12 16:34
Did you get it running using the pre-built release? If so, it may not be worth investigating your maven installation. There's not much to get from building the latest version from master.

**Comment by jin146** [comment] 2020-04-13 17:26
Yes, the pre-built release worked well after you helped me on the other issue.

**Comment by marian-m12l** [comment] 2020-04-14 19:26
Good! I'm closing the issue, but feel free to reopen if necessary.

**Closed by marian-m12l** 2020-04-14 19:26 UTC
