### ISSUE TITLE
Random option will never pick last option on Lunii

### ISSUE THREAD

**Issue by pozil** [marian-m12l/studio#142] opened 2020-11-14 19:56 UTC
**Describe the bug**
I wrote a story with a couple of random paths.
While this works fine when previewing the story in STUdio, I only get the first option all of the time on the Lunii.
I've tried the two ways to implement that (with a menu node and with an action node) but I have the same issue.

**To Reproduce**
1. Create a simple story with a menu node with two random options.
2. Deploy to Lunii and try it

**Expected behavior**
50% of the time you should get option A and 50% of the time option B.

**Actual behavior**
You only get 100% A across multiple plays.

----
**Update 2020-11-20:** it turns out that the random feature works partially but it will never pick the last option on the Lunii.

**Comment by marian-m12l** [comment] 2020-11-15 20:53
@pozil Thanks for the feedback ! I've not used this feature that much, I'll need to have a look now that I downgraded my device. When you say you always get the same option, does it mean your story pack gets through that node multiple times, or do you need to exit and reopen your pack? I don't know how the Lunii implements the randomness, but it could be that it is somewhat predictable and always "randomizes" the same way every time you run a story pack.

**Comment by pozil** [comment] 2020-11-15 22:11
I've tried several things including turning off the Lunii in between plays but that doesn't work, it always runs the first node.
Looking at your source code, I can't see where the random flag is persisted in the story pack's metadata. I worry that this "random" feature only exists in the web player. Can you check?

**Comment by marian-m12l** [comment] 2020-11-16 19:54
@pozil The random option is persisted [here](https://github.com/marian-m12l/studio/blob/master/web-ui/javascript/src/utils/writer.js#L330) as `-1`, which, to the best of my understanding, the Lunii plays as a random(-ish) option. However it's possible that the randomness is not that random, or uses a fixed seed. Have you tried to make multiple random choices on a single story? What if you run your story pack after playing another one?

**Comment by pozil** [comment] 2020-11-17 07:43
Sorry, I thought that you were serializing the story pack in Java. I was looking at [BinaryStoryPackWriter.java](https://github.com/marian-m12l/studio/blob/master/core/src/main/java/studio/core/v1/writer/binary/BinaryStoryPackWriter.java) and [ActionNode.java](https://github.com/marian-m12l/studio/blob/master/core/src/main/java/studio/core/v1/model/ActionNode.java) and couldn't find references to a "random" flag.

I tried the two test scenarii you suggested:
- multiple random choices within a story
- playing other stories in between my story tests

No luck so far. It could be a random seed problem as you suggested but what I find surprising is that it's always the first option that gets played.

Thanks for helping.

**Comment by marian-m12l** [comment] 2020-11-17 07:54
@pozil I'll need to try this. Can you share the `story.json` file of your test packs?

The editor creates the "archive" story pack and uploads it to the library. When you transfer from the library to the device, the pack is read in-memory (ArchiveStoryPackReader), assets are uncompressed (if needed), and the story pack is written in binary format using BinaryStoryPackWriter. You can see this mechanics [here](https://github.com/marian-m12l/studio/blob/master/web-ui/src/main/java/studio/webui/api/DeviceController.java#L68) and [here](https://github.com/marian-m12l/studio/blob/master/web-ui/src/main/java/studio/webui/service/LibraryService.java#L116).

**Comment by pozil** [comment] 2020-11-17 08:33
Here's a test story with two tests: one with expert nodes followed by one with a question node:
[Test_aléatoire-9cb21abf-5c97-417f-8437-f19df625aaf4-v1.zip](https://github.com/marian-m12l/studio/files/5552165/Test_aleatoire-9cb21abf-5c97-417f-8437-f19df625aaf4-v1.zip)

Thanks for the explanations, I'll take a closer look at the code.

**Comment by pozil** [comment] 2020-11-17 08:36
You'll see that you'll get a "1" displayed on the Lunii screen when it picks the first option (all of the time) or a "2" if it picks the second option (I've never seen it so far).

**Comment by marian-m12l** [comment] 2020-11-19 20:41
@pozil You story pack looks good to me, although I cannot test on the device right now. I'm wondering, did you try with more than two options?

**Comment by pozil** [comment] 2020-11-20 18:54
Great idea @marian-m12l, I ran a lot of tests with 4 options and I found that it never picks the last option.
In my original test I had only options so it would only pick the first one.
Now that I have 4, it will randomly pick 1,2,3 but never 4.

Could this be a bug on the Lunii firmware?

**Comment by marian-m12l** [comment] 2020-11-26 19:56
@pozil Good to know. I'd say it looks like a `n`/`n-1` bug in the Lunii firmware, indeed.

**Comment by ex23** [comment] 2021-02-03 12:57
Hello,

I can confirm. I encounter the same bug as @pozil . 

With a diagram like this one, you should get 50% of the time option 1 and 50% option 2. But you get 100% of the time option 1. If you try with more options, you notice that actually the Lunii never picks the last option.

![image](https://user-images.githubusercontent.com/77390400/106749978-84a38a00-6627-11eb-8288-5d6534147189.png)

**Comment by marian-m12l** [comment] 2021-02-06 20:42
@ex23 @pozil Thanks. Which versions of the lunii are you using? If the behaviour is consistent across devices, I could implement a workaround.

**Comment by pozil** [comment] 2021-02-06 22:10
Thanks for looking into this. Mine is a lunii 1.

**Comment by marian-m12l** [comment] 2021-02-25 07:35
@pozil Thanks. I don't have a way to check the behaviour on the new device. though.

**Comment by ex23** [comment] 2021-02-25 13:54
Hello. For me it's a Lunii 2. Thank you @marian-m12l for looking at this problem.

**Comment by marian-m12l** [comment] 2021-03-03 12:25
@ex23 Thanks.

Unfortunately now that I think of it I'm not sure this can be worked around. Adding a "dummy" n+1 option would allow the randomization algorithm to pick the nth option, but then this would break the navigation through all options with the wheel button...

**Comment by pozil** [comment] 2021-03-03 12:35
I agree @marian-m12l and I think that it's not a critical issue. We should probably keep the issue open so that others don't waste too much time on this.

As a workaround, I ended up asking the user to roll a dice and select the result with wheel.

**Comment by marian-m12l** [comment] 2021-03-03 12:47
@pozil Indeed this is not critical, and I'll leave the issue open.

**Comment by ex23** [comment] 2021-03-04 16:12
OK, I agree it's not critical. It's just annoying in some specific situations. But with a little bit of creativity you can live with it.

It looks indeed like a bug in the Lunii firmware itself.

**Comment by marian-m12l** [comment] 2024-06-16 22:57
I'm closing issues from past years. Feel free to reopen if needed.

**Closed by marian-m12l** 2024-06-16 22:57 UTC
